package gt.edu.umg.sistema.estudiantes.vista;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author wilso
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnIrEstudiantes = new javax.swing.JButton();
        btnIrFacturas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaption);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");

        btnIrEstudiantes.setText("Módulo de Estudiantes");
        btnIrEstudiantes.addActionListener(this::btnIrEstudiantesActionPerformed);

        btnIrFacturas.setText("Módulo Facturas");
        btnIrFacturas.setToolTipText("");
        btnIrFacturas.addActionListener(this::btnIrFacturasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIrEstudiantes)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnIrFacturas)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(btnIrEstudiantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnIrFacturas)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrEstudiantesActionPerformed
// Instanciamos y mostramos el formulario que ya tenías
        FrmEstudiante frmEstudiante = new FrmEstudiante();
        frmEstudiante.setVisible(true);       
    }//GEN-LAST:event_btnIrEstudiantesActionPerformed

    private void btnIrFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrFacturasActionPerformed
        FrmFactura frmFactura = new FrmFactura();
        frmFactura.setVisible(true);
    }//GEN-LAST:event_btnIrFacturasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIrEstudiantes;
    private javax.swing.JButton btnIrFacturas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
